export const SubscriptionDiTokens = {
  SUBSCRIPTION_SERVICE: Symbol('SUBSCRIPTION_SERVICE'),
  SUBSCRIPTION_REPOSITORY: Symbol('SUBSCRIPTION_REPOSITORY'),
  SUBSCRIPTION_MAPPER: Symbol('SUBSCRIPTION_MAPPER'),
};
