export const WeatherDiTokens = {
  WEATHER_API_PROVIDER: Symbol('WEATHER_API_PROVIDER'),
  VISUAL_CROSSING_PROVIDER: Symbol('VISUAL_CROSSING_PROVIDER'),
  WEATHER_SERVICE: Symbol('WEATHER_SERVICE'),
  WEATHER_MAPPER: Symbol('WEATHER_MAPPER'),
};
